version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mypostgres
  mypostgres:
    image: kartoza/postgis:latest
    container_name: mypostgres
    volumes:
      - mypostgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker

volumes:
  mypostgres: {}